services:
    database:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: SYMRECIPE
            MYSQL_ROOT_PASSWORD: toor
        ports:
            - "3309:3306"
        labels:
            com.symfony.server.service-ignore: true
        volumes:
            - database_data:/var/lib/mysql
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
